import { ArrowUpRight, MessageCircleReply, MessagesSquare } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { EmptyState, ErrorState, LoadingState, Pagination } from "@/components/common";
import { useDashboardCommentsQuery } from "@/hooks";
import { dashboardCommentsQuerySchema } from "@/schemas";
import { formatDate, initials, resourceLabel } from "@/utils";

export default function CommentsPage() {
  const [params, setParams] = useSearchParams();
  const state = dashboardCommentsQuerySchema.parse({ view: params.get("view") || undefined, resourceType: params.get("resourceType") || undefined, sort: params.get("sort") || undefined, page: params.get("page") || undefined, pageSize: params.get("pageSize") || undefined });
  const query = useDashboardCommentsQuery(state);
  const update = (values: Record<string, string | undefined>) => setParams((current) => { Object.entries(values).forEach(([key, value]) => value ? current.set(key, value) : current.delete(key)); if (!("page" in values)) current.set("page", "1"); return current; }, { replace: true });
  return <div className="dashboard-page comments-page"><header className="dashboard-page-heading"><div><span className="portal-kicker">Conversations</span><h1>我的评论</h1><p>查看他人给你的回复，以及你在各类资源下参与的讨论。</p></div></header><div className="comments-view-tabs" role="tablist"><button role="tab" aria-selected={state.view === "replies"} className={state.view === "replies" ? "is-active" : ""} onClick={() => update({ view: "replies" })}><MessageCircleReply size={17} />收到的回复</button><button role="tab" aria-selected={state.view === "mine"} className={state.view === "mine" ? "is-active" : ""} onClick={() => update({ view: "mine" })}><MessagesSquare size={17} />我的评论</button></div><div className="comments-filter-row"><label>资源类型<select value={state.resourceType ?? ""} onChange={(event) => update({ resourceType: event.target.value || undefined })}><option value="">全部资源</option><option value="app">应用</option><option value="skill">技能</option><option value="plugin">插件</option><option value="mcp">MCP</option></select></label><label>排序<select value={state.sort} onChange={(event) => update({ sort: event.target.value })}><option value="latest">最新优先</option><option value="oldest">最早优先</option></select></label></div><section className="dashboard-comments-region">{query.isPending ? <LoadingState label="正在加载评论" /> : query.isError ? <ErrorState retry={() => query.refetch()} /> : !query.data?.items.length ? <EmptyState title={state.view === "replies" ? "暂时没有收到回复" : "你还没有发表评论"} description="参与资源讨论后，相关内容会显示在这里。" /> : <div className="dashboard-comment-list">{query.data.items.map((item) => <article className="dashboard-comment-item" key={item.commentId}><div className="comment-avatar">{initials(item.author.displayName)}</div><div className="dashboard-comment-body"><header><div><strong>{item.author.displayName}</strong><span>{item.kind === "reply" ? "回复了你的评论" : "发表了评论"}</span></div><time>{formatDate(item.createdAt)}</time></header><p>{item.body}</p>{item.parentComment && <blockquote><strong>{item.parentComment.author.displayName}</strong>：{item.parentComment.body}</blockquote>}<Link to={item.resourceHref}><span className={`resource-type resource-type--${item.resourceType}`}>{resourceLabel(item.resourceType)}</span>{item.resourceName}<ArrowUpRight size={14} /></Link></div></article>)}</div>}</section>{query.data && query.data.total > query.data.pageSize && <Pagination page={state.page} pageSize={state.pageSize} total={query.data.total} onChange={(page) => update({ page: String(page) })} />}</div>;
}
